"""
Comprehensive Demo Script for Research Agent with Message History
Generated by Copilot
"""

import asyncio
from research_agent import run_research_query, ResearchDependencies
import logfire


async def run_comprehensive_demo():
    """Run comprehensive demo of the research agent with conversation history."""
    
    print("\n" + "=" * 80)
    print(" " * 20 + "RESEARCH AGENT DEMO")
    print(" " * 10 + "Pydantic-AI + Gemini + Logfire Integration")
    print("=" * 80 + "\n")
    
    print("✅ Using Gemini API (gemini-1.5-flash)")
    print("✅ Logfire instrumentation enabled")
    print("✅ Message history tracking enabled\n")
    
    # Create dependencies (maintains conversation across queries)
    deps = ResearchDependencies()
    print(f"📋 Session ID: {deps.session_id}")
    print(f"🔧 Max Tokens: {deps.max_tokens}\n")
    
    # Define test queries showcasing different tools
    test_queries = [
        {
            "title": "Mathematical Calculation",
            "query": "Calculate 25 * 4 + sqrt(144). Please show your work.",
            "expected_tool": "calculate"
        },
        {
            "title": "Complex Math",
            "query": "What is pow(2, 10) + sin(pi/2)?",
            "expected_tool": "calculate"
        },
        {
            "title": "Database Search - Technology",
            "query": "Search for information about artificial intelligence and machine learning in the technology category.",
            "expected_tool": "search_database"
        },
        {
            "title": "Database Search - Science",
            "query": "What is photosynthesis? Search in the science category.",
            "expected_tool": "search_database"
        },
        {
            "title": "Text Analysis - Positive Sentiment",
            "query": "Analyze the sentiment of: 'This is a wonderful and amazing product! I absolutely love it and highly recommend it. It's the best purchase I've made!'",
            "expected_tool": "analyze_data"
        },
        {
            "title": "Text Analysis - Negative Sentiment",
            "query": "Analyze the sentiment of: 'This is terrible and awful. I hate it. Worst product ever!'",
            "expected_tool": "analyze_data"
        },
        {
            "title": "Word Count Analysis",
            "query": "Count the words in this text: 'The quick brown fox jumps over the lazy dog near the riverbank.'",
            "expected_tool": "analyze_data"
        },
        {
            "title": "Current Information",
            "query": "What is the current date, time, and our session ID?",
            "expected_tool": "get_current_info"
        },
        {
            "title": "Complex Multi-Tool Query",
            "query": "First, search for DNA in the science database. Then calculate 2^8. Finally, tell me how many messages we've exchanged so far.",
            "expected_tool": "multiple"
        },
        {
            "title": "Context-Aware Follow-Up",
            "query": "Based on our previous conversation, can you remind me what the result of 2^8 was?",
            "expected_tool": "context-based"
        },
    ]
    
    # Run each query
    for i, test_case in enumerate(test_queries, 1):
        print(f"\n{'─' * 80}")
        print(f"🔍 Test {i}/{len(test_queries)}: {test_case['title']}")
        print(f"{'─' * 80}")
        print(f"\n📝 Query: {test_case['query']}")
        print(f"🛠️  Expected Tool(s): {test_case['expected_tool']}\n")
        
        try:
            # Log the query start
            with logfire.span(f'test_query_{i}', title=test_case['title']):
                logfire.info(f"Starting test query {i}: {test_case['title']}")
                
                # Run the query (deps maintains history across queries)
                response, deps = await run_research_query(test_case['query'], deps)
                
                # Display the response
                print(f"✅ Response:\n{response}\n")
                print(f"📊 History: {len(deps.message_history)} total messages")
                
                logfire.info(f"Completed test query {i}", response_preview=response[:100])
            
        except Exception as e:
            error_msg = f"❌ Error: {str(e)}"
            print(error_msg)
            logfire.error(f"Error in test query {i}: {str(e)}", exc_info=e)
    
    # Print conversation history summary
    print(f"\n\n{'=' * 80}")
    print(" " * 25 + "SESSION SUMMARY")
    print(f"{'=' * 80}\n")
    
    print(f"📊 Statistics:")
    print(f"   - Total queries executed: {len(test_queries)}")
    print(f"   - Total messages in history: {len(deps.message_history)}")
    print(f"   - Session ID: {deps.session_id}")
    print(f"   - All tool calls logged with Logfire ✓\n")
    
    # Print detailed conversation history
    print(f"\n{'=' * 80}")
    print(" " * 22 + "CONVERSATION HISTORY")
    print(f"{'=' * 80}\n")
    
    for idx, msg in enumerate(deps.message_history, 1):
        role_emoji = "👤" if msg['role'] == 'user' else "🤖" if msg['role'] == 'assistant' else "❌"
        print(f"{idx}. [{msg['timestamp']}] {role_emoji} {msg['role'].upper()}:")
        content_preview = msg['content'][:150] + "..." if len(msg['content']) > 150 else msg['content']
        print(f"   {content_preview}\n")
    
    print(f"\n{'=' * 80}")
    print(" " * 25 + "DEMO COMPLETED")
    print(f"{'=' * 80}\n")
    
    print("💡 Tips:")
    print("   - Check Logfire dashboard for detailed execution traces")
    print("   - Message history is maintained across all queries in a session")
    print("   - All tool calls are instrumented with spans and metadata")
    print("   - Error handling is comprehensive with proper logging\n")


async def simple_interactive_demo():
    """Simple interactive demo."""
    
    print("\n" + "=" * 80)
    print("SIMPLE INTERACTIVE RESEARCH AGENT")
    print("=" * 80 + "\n")
    
    deps = ResearchDependencies()
    print(f"Session ID: {deps.session_id}\n")
    
    # Simple conversation
    conversation = [
        "What is 100 + 200?",
        "Search for information about Python programming",
        "What's our session ID?",
    ]
    
    for query in conversation:
        print(f"\n👤 User: {query}")
        response, deps = await run_research_query(query, deps)
        print(f"🤖 Assistant: {response}")
    
    print(f"\n\n📊 Total messages exchanged: {len(deps.message_history)}")


if __name__ == "__main__":
    print("\n🤖 Research Agent - Pydantic-AI with Gemini & Logfire")
    print("=" * 80)
    
    # Run the comprehensive demo
    try:
        asyncio.run(run_comprehensive_demo())
    except KeyboardInterrupt:
        print("\n\n⚠️  Demo interrupted by user")
    except Exception as e:
        print(f"\n\n❌ Demo failed: {str(e)}")
        import traceback
        traceback.print_exc()
