"""
Interactive Research Agent - Takes user input and responds
Generated by Copilot
"""

import asyncio
from research_agent import run_research_query, ResearchDependencies
import logfire


async def interactive_agent():
    """Run interactive research agent that takes user queries."""
    
    print("\nResearch Agent Ready")
    print("Type your question or 'quit' to exit.\n")
    
    # Create dependencies (maintains conversation history)
    deps = ResearchDependencies()
    query_count = 0
    
    while True:
        try:
            # Get user input
            user_query = input("You: ").strip()
            
            # Check for exit commands
            if user_query.lower() in ['quit', 'exit', 'bye', 'q']:
                print("\nGoodbye!\n")
                break
            
            # Skip empty queries
            if not user_query:
                continue
            
            query_count += 1
            
            # Log the query
            with logfire.span(f'user_query_{query_count}', query=user_query):
                logfire.info(f"User query {query_count}: {user_query}")
                
                # Run the query
                response, deps = await run_research_query(user_query, deps)
                
                # Display response
                print(f"Agent: {response}\n")
                
                logfire.info(f"Query {query_count} completed", response_length=len(response))
        
        except KeyboardInterrupt:
            print("\n\nInterrupted. Exiting...\n")
            break
        
        except Exception as e:
            print(f"Error: {str(e)}\n")
            logfire.error(f"Error in query {query_count}: {str(e)}", exc_info=e)
    
    print(f"Session complete. Total queries: {query_count}\n")


def main():
    """Main entry point."""
    
    try:
        asyncio.run(interactive_agent())
    except Exception as e:
        print(f"Agent failed: {str(e)}")


if __name__ == "__main__":
    main()
