"""
Single Query Research Agent - Takes one query from command line
Generated by Copilot
"""

import asyncio
import sys
from research_agent import run_research_query, ResearchDependencies
import logfire


async def single_query(query: str):
    """Process a single research query."""
    
    print("\n" + "=" * 80)
    print(" " * 20 + "RESEARCH AGENT")
    print("=" * 80 + "\n")
    
    # Create dependencies
    deps = ResearchDependencies()
    print(f"📋 Session ID: {deps.session_id}\n")
    
    print(f"👤 Query: {query}\n")
    print(f"{'─' * 80}\n")
    
    try:
        with logfire.span('single_query', query=query):
            logfire.info(f"Processing query: {query}")
            
            # Run the query
            response, deps = await run_research_query(query, deps)
            
            # Display response
            print(f"🤖 Response:\n")
            print(f"{response}\n")
            print(f"{'─' * 80}\n")
            
            logfire.info("Query completed successfully", response_length=len(response))
            
            return response
    
    except Exception as e:
        error_msg = f"❌ Error: {str(e)}"
        print(error_msg)
        logfire.error(f"Error processing query: {str(e)}", exc_info=e)
        return None


def main():
    """Main entry point."""
    
    # Check if query provided as command line argument
    if len(sys.argv) > 1:
        query = " ".join(sys.argv[1:])
    else:
        # Ask for query if not provided
        print("\n🤖 Research Agent - Single Query Mode")
        print("=" * 80 + "\n")
        query = input("Enter your research question: ").strip()
    
    if not query:
        print("❌ No query provided. Exiting.")
        sys.exit(1)
    
    # Run the query
    asyncio.run(single_query(query))


if __name__ == "__main__":
    main()
