# Generated by Copilot
"""
Main application with FastHTML UI
State-aware e-commerce assistant with Logfire monitoring
"""

from fasthtml.common import *
import logfire
from dotenv import load_dotenv
import os
from state_manager import UIState
from gemini_agent import EcommerceAgent
import json

# Load environment variables
load_dotenv()

# Initialize Logfire (optional - will use console if not configured)
try:
    logfire.configure(send_to_logfire='if-token-present')
    logfire.info("Application starting")
except Exception as e:
    print(f"Logfire not configured, continuing without it: {e}")

# Initialize FastHTML app
app, rt = fast_app(
    hdrs=(
        Link(rel="stylesheet", href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css"),
        Script(src="https://unpkg.com/htmx.org@1.9.10"),
        Style("""
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body { 
                background: #fafafa; 
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                height: 100vh;
                overflow: hidden;
            }
            .container { 
                max-width: 1400px; 
                margin: 0 auto; 
                height: 100vh;
                display: flex;
                flex-direction: column;
            }
            
            h1 { 
                font-size: 1.5em; 
                margin: 0;
                padding: 15px 20px;
                color: #262626;
                font-weight: 600;
                background: white;
                border-bottom: 1px solid #dbdbdb;
            }
            
            h2 { font-size: 1.2em; margin: 10px 0; font-weight: 600; }
            h3 { 
                font-size: 1em; 
                margin: 0 0 12px 0; 
                font-weight: 600; 
                color: #262626; 
                padding: 12px 16px;
                background: white;
                border-bottom: 1px solid #efefef;
            }
            h4 { font-size: 0.95em; margin: 5px 0; font-weight: 600; color: #333; }
            
            p { margin: 8px 0; font-size: 0.95em; line-height: 1.4; }
            
            .chat-container { 
                display: grid; 
                grid-template-columns: 1fr 350px; 
                gap: 16px; 
                flex: 1;
                overflow: hidden;
                padding: 16px;
                background: #fafafa;
            }
            
            .chat-messages { 
                height: 100%;
                overflow-y: auto; 
                padding: 20px; 
                background: white;
                display: flex;
                flex-direction: column;
                gap: 12px;
                border-radius: 12px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            }
            
            .chat-messages::-webkit-scrollbar {
                width: 6px;
            }
            
            .chat-messages::-webkit-scrollbar-thumb {
                background: #dbdbdb;
                border-radius: 3px;
            }
            
            .message { 
                max-width: 50%;
                padding: 6px 10px; 
                border-radius: 14px; 
                font-size: 0.8em;
                line-height: 1.3;
                animation: slideIn 0.2s ease;
                word-wrap: break-word;
            }
            
            @keyframes slideIn {
                from { opacity: 0; transform: translateY(5px); }
                to { opacity: 1; transform: translateY(0); }
            }
            
            .user-message { 
                background: #3897f0;
                color: white;
                align-self: flex-end;
                border-bottom-right-radius: 4px;
            }
            
            .assistant-message { 
                background: #efefef;
                color: #262626;
                align-self: flex-start;
                border-bottom-left-radius: 4px;
            }
            
            .state-panel { 
                background: white;
                border-radius: 12px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
                height: 100%;
                overflow-y: auto;
            }
            
            .product-card { 
                border: none; 
                padding: 12px; 
                margin-bottom: 12px; 
                border-radius: 12px;
                background: white;
                box-shadow: 0 2px 8px rgba(0,0,0,0.08);
                transition: transform 0.2s, box-shadow 0.2s;
            }
            
            .product-card:hover {
                transform: translateY(-2px);
                box-shadow: 0 4px 16px rgba(102, 126, 234, 0.2);
            }
            
            .product-grid { 
                display: grid; 
                grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); 
                gap: 12px; 
                margin-top: 15px; 
            }
            
            .cart-item { 
                padding: 12px 16px; 
                border-bottom: 1px solid #efefef; 
                font-size: 0.85em;
                display: flex;
                justify-content: space-between;
                align-items: center;
            }
            
            .cart-item:last-child { border-bottom: none; }
            
            .badge { 
                display: inline-block; 
                padding: 3px 8px; 
                background: #3897f0;
                color: white; 
                border-radius: 12px;
                font-size: 0.75em;
                font-weight: 600;
            }
            
            .total { 
                font-size: 1.1em; 
                font-weight: 700; 
                color: #262626; 
                margin: 16px;
                padding: 12px;
                background: #fafafa;
                border-radius: 8px;
                text-align: center;
                border: 1px solid #efefef;
            }
            
            .chat-input-container {
                padding: 10px 14px;
                background: white;
                border-top: 1px solid #efefef;
                border-radius: 0 0 12px 12px;
            }
            
            input[type="text"] { 
                width: 100%; 
                padding: 8px 14px; 
                border: 1px solid #dbdbdb;
                border-radius: 20px;
                font-size: 0.85em;
                outline: none;
                transition: border-color 0.2s;
                background: #fafafa;
            }
            
            input[type="text"]:focus {
                border-color: #3897f0;
                background: white;
            }
            
            button { 
                margin-left: 8px; 
                padding: 3px 3px;
                font-size: 0.65em;
                font-weight: 600;
                border: none;
                border-radius: 4px;
                cursor: pointer;
                transition: all 0.2s;
                background: #3897f0;
                color: white;
                line-height: 1.2;
    
            }
                color: white;
                line-height: 1.2;
            }
            
            button:hover {
                background: #1372cc;
            }
            
            button:active {
                transform: scale(0.98);
            }
            
            .remove-btn {
                all: unset !important;
                background: #ed4956 !important;
                color: white !important;
                padding: 0 !important;
                font-size: 1.2em !important;
                border-radius: 50% !important;
                height: 24px !important;
                width: 24px !important;
                min-width: 24px !important;
                max-width: 24px !important;
                min-height: 24px !important;
                max-height: 24px !important;
                display: inline-flex !important;
                align-items: center !important;
                justify-content: center !important;
                margin: 0 !important;
                border: none !important;
                cursor: pointer !important;
                line-height: 1 !important;
                box-sizing: border-box !important;
            }
            
            .remove-btn:hover {
                background: #c92f3a !important;
                transform: scale(1.1) !important;
            }
            
            .remove-btn:active {
                transform: scale(0.95) !important;
            }
            
            hr { 
                border: none; 
                height: 1px; 
                background: #dbdbdb; 
                margin: 20px 0; 
            }
            
            strong { font-weight: 600; color: #262626; }
            
            .example-prompts {
                background: white;
                padding: 12px 20px;
                border-bottom: 1px solid #dbdbdb;
                font-size: 0.8em;
                color: #8e8e8e;
                display: flex;
                align-items: center;
                gap: 8px;
                flex-wrap: wrap;
            }
            
            .example-prompts strong {
                color: #262626;
                font-size: 0.9em;
            }
            
            .cart-chips {
                display: flex;
                gap: 6px;
                flex-wrap: wrap;
                padding: 8px 20px;
                background: #fafafa;
                border-bottom: 1px solid #dbdbdb;
                min-height: 40px;
                align-items: center;
            }
            
            .cart-chip {
                display: inline-flex;
                align-items: center;
                gap: 6px;
                padding: 4px 10px;
                background: white;
                border: 1px solid #dbdbdb;
                border-radius: 16px;
                font-size: 0.75em;
                color: #262626;
                box-shadow: 0 1px 3px rgba(0,0,0,0.05);
            }
            
            .cart-chip-quantity {
                background: #3897f0;
                color: white;
                padding: 2px 6px;
                border-radius: 10px;
                font-weight: 600;
                font-size: 0.9em;
            }
            
            .cart-chips-empty {
                color: #8e8e8e;
                font-size: 0.8em;
            }
            
            .empty-cart {
                text-align: center;
                padding: 40px 20px;
                color: #8e8e8e;
                font-size: 0.9em;
            }
            
            .empty-cart svg {
                width: 60px;
                height: 60px;
                margin-bottom: 12px;
                opacity: 0.3;
            }
        """)
    ),
    live=True
)

# Initialize state and agent
state = UIState()
api_key = os.getenv("GEMINI_API_KEY", "AIzaSyAJ0-aZ1knp4YejSe5RUvX6mEKMb_9r22A")
agent = EcommerceAgent(api_key=api_key, state=state)

# Store conversation history
conversation_history = []


def render_state_panel():
    """Render the current UI state panel"""
    return Div(
        H3("🎯 Current UI State"),
        Pre(
            f"Current View: {state.current_view}\n"
            f"Products in Catalog: {len(state.products)}\n"
            f"Categories: {', '.join(state.get_categories())}\n"
            f"Cart Items: {len(state.cart)}\n"
            f"Cart Total: ₹{state.get_cart_total():.2f}\n"
            f"Active Filters: {state.active_filters if state.active_filters else 'None'}\n"
            f"Search Query: {state.search_query if state.search_query else 'None'}\n"
            f"Selected Category: {state.selected_category if state.selected_category else 'All'}",
            style="background: #f5f5f5; padding: 10px; border-radius: 5px; font-size: 0.9em;"
        ),
        cls="state-panel"
    )


def render_cart_chips():
    """Render cart items as chips"""
    if not state.cart:
        return Div(
            "🛒 Cart is empty",
            cls="cart-chips-empty"
        )
    
    chips = []
    for item in state.cart:
        chips.append(
            Div(
                Span(item.product_name),
                Span(str(item.quantity), cls="cart-chip-quantity"),
                Span(f"₹{item.subtotal:.0f}"),
                cls="cart-chip"
            )
        )
    
    return Div(*chips)


def render_cart_panel():
    """Render the shopping cart panel"""
    if not state.cart:
        cart_content = Div(
            "🛒",
            Br(),
            "Your cart is empty",
            cls="empty-cart"
        )
    else:
        cart_items = [
            Div(
                Div(
                    Strong(item.product_name),
                    Br(),
                    Span(f"{item.quantity} × ₹{item.price:.2f}", style="color: #8e8e8e; font-size: 0.85em;")
                ),
                Div(
                    Span(f"₹{item.subtotal:.2f}", style="font-weight: 600; color: #262626; margin-right: 8px;"),
                    Button("×",
                           hx_post=f"/remove-item/{item.product_id}",
                           hx_target="#main-container",
                           hx_swap="innerHTML",
                           cls="remove-btn",
                           title=f"Remove {item.product_name}")
                ),
                cls="cart-item",
                style="display: flex; justify-content: space-between; align-items: center;"
            )
            for item in state.cart
        ]
        cart_content = Div(
            *cart_items,
            Div(f"Total: ₹{state.get_cart_total():.2f}", cls="total")
        )
    
    return Div(
        H3("🛒 Cart"),
        cart_content,
        cls="state-panel"
    )


def render_products():
    """Render product catalog"""
    if state.search_query:
        products = state.search_products(state.search_query)
        title = f"Search Results for '{state.search_query}'"
    elif state.selected_category:
        products = state.filter_products(category=state.selected_category)
        title = f"{state.selected_category} Products"
    else:
        products = state.products
        title = "All Products"
    
    if not products:
        return Div(H3(title), P("No products found."))
    
    product_cards = [
        Div(
            H4(f"{p.name}", Span(f"ID: {p.id}", cls="badge", style="float: right; font-size: 0.7em;")),
            P(Strong(f"₹{p.price:.2f}"), style="font-size: 1.2em; color: #2196f3;"),
            P(f"Category: {p.category}"),
            P(f"Rating: {'⭐' * int(p.rating)} ({p.rating})"),
            P(f"Stock: {p.stock} units"),
            P(p.description, style="color: #666; font-size: 0.9em;"),
            cls="product-card"
        )
        for p in products
    ]
    
    return Div(
        H3(title),
        Div(*product_cards, cls="product-grid")
    )


def render_chat_messages():
    """Render chat message history"""
    if not conversation_history:
        return Div(
            Div(
                "👋",
                Br(),
                "Start a conversation!",
                Br(),
                Span("Ask about products or add items to your cart", style="color: #8e8e8e; font-size: 0.85em;"),
                style="text-align: center; color: #262626; padding: 60px 40px;"
            ),
            cls="chat-messages",
            id="chat-messages"
        )
    
    messages = []
    for msg in conversation_history:
        if msg["role"] == "user":
            messages.append(
                Div(msg["content"], cls="message user-message")
            )
        else:
            messages.append(
                Div(msg["content"], cls="message assistant-message")
            )
    
    return Div(*messages, cls="chat-messages", id="chat-messages")


@rt("/")
def get():
    """Main page"""
    return Title("E-Commerce AI Assistant"), Main(
        Div(
            H1("🛍️ Shopping Assistant"),
            
            # Cart chips
            Div(
                render_cart_chips(),
                cls="cart-chips"
            ),
            
            # Example prompts
            Div(
                Strong("💬 Try: "),
                "'Add banana' • 'Show electronics' • 'What's in my cart?'",
                cls="example-prompts"
            ),
            
            # Chat interface
            Div(
                # Left column - Chat
                Div(
                    render_chat_messages(),
                    Div(
                        Form(
                            Input(
                                type="text",
                                name="message",
                                placeholder="Message...",
                                required=True,
                                autofocus=True
                            ),
                            Button("Send", type="submit"),
                            Button("Reset", 
                                   hx_post="/reset",
                                   hx_target="#main-container",
                                   hx_swap="innerHTML",
                                   type="button",
                                   style="background: #dbdbdb; color: #262626;"),
                            style="display: flex; gap: 8px;",
                            hx_post="/chat",
                            hx_target="#main-container",
                            hx_swap="innerHTML"
                        ),
                        cls="chat-input-container"
                    ),
                    style="display: flex; flex-direction: column; height: 100%; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);"
                ),
                
                # Right column - Cart panel
                render_cart_panel(),
                
                cls="chat-container"
            ),
            
            cls="container",
            id="main-container"
        )
    )


@rt("/chat")
async def post(message: str):
    """Handle chat message"""
    logfire.info("Processing chat message", message=message)
    
    # Add user message to history
    conversation_history.append({"role": "user", "content": message})
    
    # Process with agent
    response = agent.process_message(message)
    
    # Add assistant response to history
    conversation_history.append({"role": "assistant", "content": response})
    
    logfire.info("Chat response generated", 
                cart_items=len(state.cart),
                cart_total=state.get_cart_total())
    
    # Return updated UI
    return Div(
        H1("🛍️ Shopping Assistant"),
        
        Div(
            render_cart_chips(),
            cls="cart-chips"
        ),
        
        Div(
            Strong("💬 Try: "),
            "'Add banana' • 'Show electronics' • 'What's in my cart?'",
            cls="example-prompts"
        ),
        
        Div(
            Div(
                render_chat_messages(),
                Div(
                    Form(
                        Input(
                            type="text",
                            name="message",
                            placeholder="Message...",
                            required=True,
                            autofocus=True
                        ),
                        Button("Send", type="submit"),
                        Button("Reset", 
                               hx_post="/reset",
                               hx_target="#main-container",
                               hx_swap="innerHTML",
                               type="button",
                               style="background: #dbdbdb; color: #262626;"),
                        style="display: flex; gap: 8px;",
                        hx_post="/chat",
                        hx_target="#main-container",
                        hx_swap="innerHTML"
                    ),
                    cls="chat-input-container"
                ),
                style="display: flex; flex-direction: column; height: 100%; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);"
            ),
            
            render_cart_panel(),
            
            cls="chat-container"
        ),
        
        cls="container"
    )


@rt("/reset")
def post():
    """Reset conversation and state"""
    global state, agent, conversation_history
    
    logfire.info("Resetting conversation")
    
    # Reset state and agent
    state = UIState()
    agent = EcommerceAgent(api_key=api_key, state=state)
    conversation_history.clear()
    
    # Return fresh UI
    return Div(
        H1("🛍️ Shopping Assistant"),
        
        Div(
            render_cart_chips(),
            cls="cart-chips"
        ),
        
        Div(
            Strong("💬 Try: "),
            "'Add banana' • 'Show electronics' • 'What's in my cart?'",
            cls="example-prompts"
        ),
        
        Div(
            Div(
                render_chat_messages(),
                Div(
                    Form(
                        Input(
                            type="text",
                            name="message",
                            placeholder="Message...",
                            required=True,
                            autofocus=True
                        ),
                        Button("Send", type="submit"),
                        style="display: flex; gap: 8px;",
                        hx_post="/chat",
                        hx_target="#main-container",
                        hx_swap="innerHTML"
                    ),
                    cls="chat-input-container"
                ),
                style="display: flex; flex-direction: column; height: 100%; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);"
            ),
            
            render_cart_panel(),
            
            cls="chat-container"
        ),
        
        cls="container"
    )


@rt("/remove-item/{product_id}")
def post(product_id: str):
    """Remove item from cart"""
    logfire.info("Removing item from cart", product_id=product_id)
    
    # Remove item from cart (convert string to int)
    state.remove_from_cart(int(product_id))
    
    # Return updated UI
    return Div(
        H1("🛍️ Shopping Assistant"),
        
        Div(
            render_cart_chips(),
            cls="cart-chips"
        ),
        
        Div(
            Strong("💬 Try: "),
            "'Add banana' • 'Show electronics' • 'What's in my cart?'",
            cls="example-prompts"
        ),
        
        Div(
            Div(
                render_chat_messages(),
                Div(
                    Form(
                        Input(
                            type="text",
                            name="message",
                            placeholder="Message...",
                            required=True,
                            autofocus=True
                        ),
                        Button("Send", type="submit"),
                        style="display: flex; gap: 8px;",
                        hx_post="/chat",
                        hx_target="#main-container",
                        hx_swap="innerHTML"
                    ),
                    cls="chat-input-container"
                ),
                style="display: flex; flex-direction: column; height: 100%; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);"
            ),
            
            render_cart_panel(),
            
            cls="chat-container"
        ),
        
        cls="container"
    )


if __name__ == "__main__":
    logfire.info("Launching FastHTML application")
    serve()
