# Generated by Copilot
"""
Demo script showing example conversations for the state-aware e-commerce agent
"""

EXAMPLE_CONVERSATIONS = """
===========================================
DEMO CONVERSATION EXAMPLES
===========================================

Example 1: Shopping Flow (4 turns)
-------------------------------------------
Turn 1 (Browse):
User: "Show me electronics products"
Agent: Filters products to Electronics category, displays Smart Watch, Wireless Headphones, Bluetooth Speaker

Turn 2 (Add to Cart):
User: "Add the wireless headphones to my cart"
Agent: Adds product ID 1 to cart, updates cart total to $79.99

Turn 3 (View Cart):
User: "What's in my cart?"
Agent: Shows cart with 1 item (Wireless Headphones), total $79.99

Turn 4 (Modify):
User: "Add 2 bluetooth speakers too"
Agent: Adds 2x Bluetooth Speaker (ID 7), updates cart total to $199.97


Example 2: Search and Filter (3 turns)
-------------------------------------------
Turn 1:
User: "I'm looking for sports equipment"
Agent: Filters by Sports category, shows Running Shoes and Yoga Mat

Turn 2:
User: "Show me items under $50"
Agent: Applies price filter, shows Yoga Mat ($29.99)

Turn 3:
User: "Add the yoga mat to my cart"
Agent: Adds Yoga Mat to cart, maintains Sports filter


Example 3: Product Discovery (4 turns)
-------------------------------------------
Turn 1:
User: "Tell me about the smart watch"
Agent: Retrieves product details for Smart Watch (ID 5)

Turn 2:
User: "Add it to my cart"
Agent: Adds Smart Watch ($199.99) to cart

Turn 3:
User: "What else do you have in Electronics?"
Agent: Shows all Electronics products

Turn 4:
User: "Show me my total"
Agent: Displays cart summary with total


Example 4: Multi-Category Shopping (5 turns)
-------------------------------------------
Turn 1:
User: "I need a coffee maker"
Agent: Searches for "coffee", finds Coffee Maker in Home category

Turn 2:
User: "Add it to my cart"
Agent: Adds Coffee Maker ($49.99) to cart

Turn 3:
User: "Do you have any backpacks?"
Agent: Searches for "backpack", finds Backpack in Accessories

Turn 4:
User: "Add that too"
Agent: Adds Backpack ($45.99) to cart

Turn 5:
User: "Show my cart and total"
Agent: Displays both items, total $95.98


Try these in the Gradio interface to see:
- Real-time UI state updates
- Cart management
- Product filtering and search
- Multi-turn conversation with context
- Logfire monitoring of all operations
"""

if __name__ == "__main__":
    print(EXAMPLE_CONVERSATIONS)
