# Generated by Copilot
"""
Gemini-powered E-commerce Agent with Function Calling
Handles natural language interactions and UI state manipulation
"""

import google.generativeai as genai
from typing import Dict, Any, List, Callable
import json
import logfire
from state_manager import UIState


class EcommerceAgent:
    """AI Agent for e-commerce interactions using Gemini"""
    
    def __init__(self, api_key: str, state: UIState):
        """Initialize agent with Gemini API and state manager"""
        genai.configure(api_key=api_key)
        self.state = state
        self.model = genai.GenerativeModel(
            'gemini-2.5-flash',
            tools=[self._get_function_declarations()]
        )
        # Disable automatic function calling - we'll handle it manually
        self.chat = self.model.start_chat(enable_automatic_function_calling=False)
        
        # Map function names to actual methods
        self.function_map: Dict[str, Callable] = {
            "add_to_cart": self._add_to_cart,
            "add_custom_product": self._add_custom_product,
            "remove_from_cart": self._remove_from_cart,
            "view_cart": self._view_cart,
            "search_products": self._search_products,
            "filter_by_category": self._filter_by_category,
            "get_product_details": self._get_product_details,
            "clear_cart": self._clear_cart,
            "change_view": self._change_view,
            "list_categories": self._list_categories,
            "get_state_info": self._get_state_info,
        }
        
        logfire.info("Gemini Agent initialized", model="gemini-1.5-flash")
    
    def _get_function_declarations(self) -> List[Dict[str, Any]]:
        """Define available functions for the agent"""
        return [
            {
                "name": "add_to_cart",
                "description": "Add a product to the shopping cart by product ID (only use if you know the exact product ID from the catalog)",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "product_id": {
                            "type": "integer",
                            "description": "The ID of the product to add"
                        },
                        "quantity": {
                            "type": "integer",
                            "description": "Quantity to add (default 1)"
                        }
                    },
                    "required": ["product_id"]
                }
            },
            {
                "name": "add_custom_product",
                "description": "Add a custom product to cart that is not in the catalog. Use this when the user wants to add any product that doesn't exist in our catalog. AUTOMATICALLY estimate a reasonable price in Indian Rupees (₹) based on typical market prices: Fruits/Vegetables (₹20-100), Groceries (₹50-300), Electronics (₹500-50000), Clothing (₹300-3000), Books (₹200-800). DO NOT ask the user for the price.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "description": "The name of the custom product"
                        },
                        "price": {
                            "type": "number",
                            "description": "Estimated price in Indian Rupees (₹). Use typical Indian market prices."
                        },
                        "quantity": {
                            "type": "integer",
                            "description": "Quantity to add (default 1)"
                        }
                    },
                    "required": ["name", "price"]
                }
            },
            {
                "name": "remove_from_cart",
                "description": "Remove a product from the shopping cart",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "product_id": {
                            "type": "integer",
                            "description": "The ID of the product to remove"
                        }
                    },
                    "required": ["product_id"]
                }
            },
            {
                "name": "view_cart",
                "description": "View the current shopping cart contents and total",
                "parameters": {
                    "type": "object",
                    "properties": {}
                }
            },
            {
                "name": "search_products",
                "description": "Search for products by name or description",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "Search query"
                        }
                    },
                    "required": ["query"]
                }
            },
            {
                "name": "filter_by_category",
                "description": "Filter products by category",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "category": {
                            "type": "string",
                            "description": "Category name (Electronics, Sports, Home, Accessories)"
                        }
                    },
                    "required": ["category"]
                }
            },
            {
                "name": "get_product_details",
                "description": "Get detailed information about a specific product",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "product_id": {
                            "type": "integer",
                            "description": "The ID of the product"
                        }
                    },
                    "required": ["product_id"]
                }
            },
            {
                "name": "clear_cart",
                "description": "Remove all items from the shopping cart",
                "parameters": {
                    "type": "object",
                    "properties": {}
                }
            },
            {
                "name": "change_view",
                "description": "Change the current UI view (products, cart, or checkout)",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "view": {
                            "type": "string",
                            "description": "View name: products, cart, or checkout"
                        }
                    },
                    "required": ["view"]
                }
            },
            {
                "name": "list_categories",
                "description": "List all available product categories",
                "parameters": {
                    "type": "object",
                    "properties": {}
                }
            },
            {
                "name": "get_state_info",
                "description": "Get current UI state information including view, cart status, and filters",
                "parameters": {
                    "type": "object",
                    "properties": {}
                }
            }
        ]
    
    @logfire.instrument("add_to_cart")
    def _add_to_cart(self, product_id: int, quantity: int = 1) -> str:
        """Add product to cart"""
        result = self.state.add_to_cart(product_id, quantity)
        logfire.info("Cart operation", operation="add", product_id=product_id, 
                    quantity=quantity, success=result["success"])
        return json.dumps(result)
    
    @logfire.instrument("add_custom_product")
    def _add_custom_product(self, name: str, price: float, quantity: int = 1) -> str:
        """Add custom product to cart"""
        # Check if this product name already exists in the catalog
        existing_product = None
        for product in self.state.products:
            if product.name.lower() == name.lower():
                existing_product = product
                break
        
        if existing_product:
            # Use existing product instead of creating duplicate
            result = self.state.add_to_cart(existing_product.id, quantity)
        else:
            # Create new custom product
            result = self.state.add_custom_product_to_cart(name, price, quantity)
        
        logfire.info("Custom product added", name=name, price=price, quantity=quantity)
        return json.dumps(result)
    
    @logfire.instrument("remove_from_cart")
    def _remove_from_cart(self, product_id: int) -> str:
        """Remove product from cart"""
        result = self.state.remove_from_cart(product_id)
        logfire.info("Cart operation", operation="remove", product_id=product_id)
        return json.dumps(result)
    
    @logfire.instrument("view_cart")
    def _view_cart(self) -> str:
        """View cart contents"""
        cart_info = {
            "items": [
                {
                    "product_id": item.product_id,
                    "name": item.product_name,
                    "quantity": item.quantity,
                    "price": item.price,
                    "subtotal": item.subtotal
                }
                for item in self.state.cart
            ],
            "total": self.state.get_cart_total(),
            "item_count": len(self.state.cart)
        }
        logfire.info("View cart", item_count=len(self.state.cart), 
                    total=self.state.get_cart_total())
        return json.dumps(cart_info)
    
    @logfire.instrument("search_products")
    def _search_products(self, query: str) -> str:
        """Search products"""
        results = self.state.search_products(query)
        products_info = [
            {
                "id": p.id,
                "name": p.name,
                "category": p.category,
                "price": p.price,
                "rating": p.rating,
                "stock": p.stock
            }
            for p in results
        ]
        logfire.info("Search products", query=query, results_count=len(results))
        return json.dumps({"query": query, "results": products_info, "count": len(results)})
    
    @logfire.instrument("filter_by_category")
    def _filter_by_category(self, category: str) -> str:
        """Filter products by category"""
        results = self.state.filter_products(category=category)
        products_info = [
            {
                "id": p.id,
                "name": p.name,
                "price": p.price,
                "rating": p.rating,
                "stock": p.stock
            }
            for p in results
        ]
        logfire.info("Filter by category", category=category, results_count=len(results))
        return json.dumps({"category": category, "products": products_info, "count": len(results)})
    
    @logfire.instrument("get_product_details")
    def _get_product_details(self, product_id: int) -> str:
        """Get product details"""
        product = self.state.get_product_by_id(product_id)
        if not product:
            return json.dumps({"error": "Product not found"})
        
        product_info = {
            "id": product.id,
            "name": product.name,
            "category": product.category,
            "price": product.price,
            "description": product.description,
            "rating": product.rating,
            "stock": product.stock
        }
        logfire.info("Get product details", product_id=product_id)
        return json.dumps(product_info)
    
    @logfire.instrument("clear_cart")
    def _clear_cart(self) -> str:
        """Clear cart"""
        result = self.state.clear_cart()
        logfire.info("Clear cart")
        return json.dumps(result)
    
    @logfire.instrument("change_view")
    def _change_view(self, view: str) -> str:
        """Change UI view"""
        result = self.state.change_view(view)
        logfire.info("Change view", view=view, success=result["success"])
        return json.dumps(result)
    
    def _list_categories(self) -> str:
        """List all categories"""
        categories = self.state.get_categories()
        logfire.info("List categories", count=len(categories))
        return json.dumps({"categories": categories})
    
    def _get_state_info(self) -> str:
        """Get current state info"""
        state_info = {
            "current_view": self.state.current_view,
            "cart_items": len(self.state.cart),
            "cart_total": self.state.get_cart_total(),
            "selected_category": self.state.selected_category,
            "search_query": self.state.search_query,
            "total_products": len(self.state.products)
        }
        logfire.info("Get state info", **state_info)
        return json.dumps(state_info)
    
    @logfire.instrument("process_message")
    def process_message(self, user_message: str) -> str:
        """Process user message and return agent response"""
        logfire.info("Processing user message", message=user_message)
        
        # Add to conversation history
        self.state.add_conversation_message("user", user_message)
        
        try:
            # Send message to Gemini
            response = self.chat.send_message(user_message)
            
            # Check if model wants to call functions
            function_calls_made = []
            if response.candidates and response.candidates[0].content.parts:
                for part in response.candidates[0].content.parts:
                    if hasattr(part, 'function_call') and part.function_call:
                        function_call = part.function_call
                        function_name = function_call.name
                        function_args = dict(function_call.args)
                        
                        logfire.info("Function call detected", function=function_name, args=function_args)
                        print(f"DEBUG: Calling {function_name} with {function_args}")
                        
                        # Execute the function
                        if function_name in self.function_map:
                            result = self.function_map[function_name](**function_args)
                            print(f"DEBUG: Function result: {result}")
                            print(f"DEBUG: Cart after call: {len(self.state.cart)} items")
                            
                            function_calls_made.append({
                                "name": function_name,
                                "result": result
                            })
                        else:
                            print(f"DEBUG: Function {function_name} not found in function_map")
            
            # If functions were called, send results back to get final response
            if function_calls_made:
                # Build function response
                function_response_parts = []
                for fc in function_calls_made:
                    function_response_parts.append(
                        genai.protos.Part(
                            function_response=genai.protos.FunctionResponse(
                                name=fc["name"],
                                response={"result": fc["result"]}
                            )
                        )
                    )
                
                response = self.chat.send_message(
                    genai.protos.Content(parts=function_response_parts)
                )
            
            # Extract text response
            response_text = ""
            try:
                if hasattr(response, 'text'):
                    response_text = response.text
            except:
                if hasattr(response, 'candidates') and response.candidates:
                    candidate = response.candidates[0]
                    if hasattr(candidate, 'content') and hasattr(candidate.content, 'parts'):
                        for part in candidate.content.parts:
                            if hasattr(part, 'text') and part.text:
                                response_text += part.text
            
            if not response_text:
                response_text = f"✅ Done! Your cart now has {len(self.state.cart)} item(s). Total: ${self.state.get_cart_total():.2f}"
            
            print(f"DEBUG: Final cart count: {len(self.state.cart)}")
            
            # Add to conversation history
            self.state.add_conversation_message("assistant", response_text)
            
            logfire.info("Agent response generated", 
                        response_length=len(response_text),
                        cart_items=len(self.state.cart))
            
            return response_text
            
        except Exception as e:
            import traceback
            error_detail = traceback.format_exc()
            print(f"DEBUG ERROR: {error_detail}")
            error_msg = f"Sorry, I encountered an error. Please try again."
            logfire.error("Agent error", error=str(e), traceback=error_detail)
            self.state.add_conversation_message("assistant", error_msg)
            return error_msg
    
    def get_system_prompt(self) -> str:
        """Get system prompt for the agent"""
        return f"""You are a helpful e-commerce shopping assistant for an Indian marketplace. You can help users:
- Browse and search products from the catalog
- Add items from the catalog to cart using add_to_cart with product ID
- Add ANY custom products to cart using add_custom_product (automatically estimate Indian Rupee prices)
- View and manage their shopping cart
- Get product recommendations
- Filter products by category
- View product details

Current product categories in catalog: {', '.join(self.state.get_categories())}

Available products in catalog:
{chr(10).join([f"- {p.name} (ID: {p.id}, ₹{p.price:.2f})" for p in self.state.products[:15]])}

CRITICAL INSTRUCTIONS FOR CUSTOM PRODUCTS:
When a user wants to add a product NOT in the catalog, IMMEDIATELY call add_custom_product with:
1. The product name from user's request
2. A reasonable price in Indian Rupees based on typical market rates:
   - Fruits (Apple, Mango, etc.): ₹40-80 per kg
   - Vegetables (Tomato, Onion, etc.): ₹20-60 per kg
   - Dairy (Milk, Cheese, etc.): ₹50-200
   - Snacks/Packaged food: ₹30-150
   - Beverages: ₹20-100
   - Personal care: ₹100-500
   - Household items: ₹50-300
   - Electronics: ₹1000-50000
   - Clothing: ₹500-3000

IMPORTANT: If user says "add more X" or "add another X" where X is already in cart, 
call the function with quantity=1 and the system will automatically increase the existing item's quantity.

DO NOT ask the user what price they want. Automatically estimate based on the product type.

Always be friendly, helpful, and proactive in suggesting products or actions.
When users ask for products not in the catalog, add them immediately with estimated prices.
Provide clear information about cart contents and totals when relevant.
"""
