# Generated by Copilot
"""
State Management System for E-commerce Assistant
Tracks UI state including cart, products, filters, and conversation history
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from datetime import datetime
import json


class Product(BaseModel):
    """Product model"""
    id: int
    name: str
    category: str
    price: float
    stock: int
    description: str
    rating: float = 4.0


class CartItem(BaseModel):
    """Cart item model"""
    product_id: int
    product_name: str
    quantity: int
    price: float
    
    @property
    def subtotal(self) -> float:
        return self.quantity * self.price


class UIState(BaseModel):
    """Complete UI state for the e-commerce application"""
    
    # Product catalog
    products: List[Product] = Field(default_factory=list)
    
    # Shopping cart
    cart: List[CartItem] = Field(default_factory=list)
    
    # Filters and search
    active_filters: Dict[str, Any] = Field(default_factory=dict)
    search_query: Optional[str] = None
    
    # UI display state
    current_view: str = "products"  # products, cart, checkout
    selected_category: Optional[str] = None
    sort_by: str = "name"  # name, price, rating
    
    # Conversation history
    conversation_history: List[Dict[str, str]] = Field(default_factory=list)
    
    # User preferences
    user_preferences: Dict[str, Any] = Field(default_factory=dict)
    
    class Config:
        arbitrary_types_allowed = True
    
    def __init__(self, **data):
        super().__init__(**data)
        if not self.products:
            self._initialize_products()
    
    def _initialize_products(self):
        """Initialize sample product catalog"""
        self.products = [
            Product(id=1, name="Wireless Headphones", category="Electronics", 
                   price=79.99, stock=15, description="High-quality noise-cancelling headphones", rating=4.5),
            Product(id=2, name="Running Shoes", category="Sports", 
                   price=89.99, stock=25, description="Comfortable running shoes for all terrains", rating=4.7),
            Product(id=3, name="Coffee Maker", category="Home", 
                   price=49.99, stock=10, description="Programmable coffee maker with timer", rating=4.3),
            Product(id=4, name="Yoga Mat", category="Sports", 
                   price=29.99, stock=30, description="Non-slip yoga mat with carrying strap", rating=4.6),
            Product(id=5, name="Smart Watch", category="Electronics", 
                   price=199.99, stock=8, description="Fitness tracker with heart rate monitor", rating=4.4),
            Product(id=6, name="Backpack", category="Accessories", 
                   price=45.99, stock=20, description="Durable backpack with laptop compartment", rating=4.2),
            Product(id=7, name="Bluetooth Speaker", category="Electronics", 
                   price=59.99, stock=12, description="Portable waterproof speaker", rating=4.5),
            Product(id=8, name="Cooking Set", category="Home", 
                   price=119.99, stock=7, description="Professional 10-piece cooking set", rating=4.8),
            Product(id=9, name="Organic Bananas", category="Food", 
                   price=3.99, stock=50, description="Fresh organic bananas - 1 bunch", rating=4.6),
            Product(id=10, name="Fresh Strawberries", category="Food", 
                   price=5.99, stock=40, description="Sweet and juicy strawberries - 1 lb", rating=4.7),
            Product(id=11, name="Whole Grain Bread", category="Food", 
                   price=4.49, stock=35, description="Freshly baked whole grain bread", rating=4.5),
            Product(id=12, name="Greek Yogurt", category="Food", 
                   price=6.99, stock=45, description="Creamy Greek yogurt - 32 oz", rating=4.6),
        ]
    
    def add_to_cart(self, product_id: int, quantity: int = 1) -> Dict[str, Any]:
        """Add product to cart"""
        product = next((p for p in self.products if p.id == product_id), None)
        if not product:
            return {"success": False, "message": f"Product {product_id} not found"}
        
        if product.stock < quantity:
            return {"success": False, "message": f"Insufficient stock for {product.name}"}
        
        # Check if product already in cart
        existing_item = next((item for item in self.cart if item.product_id == product_id), None)
        if existing_item:
            existing_item.quantity += quantity
        else:
            cart_item = CartItem(
                product_id=product.id,
                product_name=product.name,
                quantity=quantity,
                price=product.price
            )
            self.cart.append(cart_item)
        
        return {"success": True, "message": f"Added {product.name} to cart"}
    
    def add_custom_product_to_cart(self, name: str, price: float, quantity: int = 1) -> Dict[str, Any]:
        """Add a dynamically created product to cart"""
        # Create a new product ID
        new_id = max([p.id for p in self.products]) + 1 if self.products else 1
        
        # Create the new product
        new_product = Product(
            id=new_id,
            name=name,
            category="Custom",
            price=price,
            stock=100,  # Set high stock for dynamic products
            description=f"Custom item: {name}",
            rating=4.0
        )
        
        # Add to product catalog
        self.products.append(new_product)
        
        # Add to cart
        return self.add_to_cart(new_id, quantity)
        
        if product.stock < quantity:
            return {"success": False, "message": f"Only {product.stock} items in stock"}
        
        # Check if product already in cart
        existing_item = next((item for item in self.cart if item.product_id == product_id), None)
        if existing_item:
            existing_item.quantity += quantity
        else:
            self.cart.append(CartItem(
                product_id=product.id,
                product_name=product.name,
                quantity=quantity,
                price=product.price
            ))
        
        return {
            "success": True, 
            "message": f"Added {quantity}x {product.name} to cart",
            "cart_total": self.get_cart_total()
        }
    
    def remove_from_cart(self, product_id: int) -> Dict[str, Any]:
        """Remove product from cart"""
        self.cart = [item for item in self.cart if item.product_id != product_id]
        return {"success": True, "message": "Item removed from cart"}
    
    def update_cart_quantity(self, product_id: int, quantity: int) -> Dict[str, Any]:
        """Update quantity of item in cart"""
        item = next((item for item in self.cart if item.product_id == product_id), None)
        if not item:
            return {"success": False, "message": "Item not in cart"}
        
        if quantity <= 0:
            return self.remove_from_cart(product_id)
        
        item.quantity = quantity
        return {"success": True, "message": f"Updated quantity to {quantity}"}
    
    def clear_cart(self) -> Dict[str, Any]:
        """Clear all items from cart"""
        self.cart.clear()
        return {"success": True, "message": "Cart cleared"}
    
    def get_cart_total(self) -> float:
        """Calculate total cart value"""
        return sum(item.subtotal for item in self.cart)
    
    def get_cart_summary(self) -> str:
        """Get formatted cart summary"""
        if not self.cart:
            return "Cart is empty"
        
        summary = f"Cart ({len(self.cart)} items):\n"
        for item in self.cart:
            summary += f"  - {item.product_name}: {item.quantity}x ${item.price:.2f} = ${item.subtotal:.2f}\n"
        summary += f"Total: ${self.get_cart_total():.2f}"
        return summary
    
    def filter_products(self, category: Optional[str] = None, 
                       min_price: Optional[float] = None,
                       max_price: Optional[float] = None) -> List[Product]:
        """Filter products based on criteria"""
        filtered = self.products
        
        if category:
            self.selected_category = category
            filtered = [p for p in filtered if p.category.lower() == category.lower()]
        
        if min_price is not None:
            filtered = [p for p in filtered if p.price >= min_price]
        
        if max_price is not None:
            filtered = [p for p in filtered if p.price <= max_price]
        
        return filtered
    
    def search_products(self, query: str) -> List[Product]:
        """Search products by name or description"""
        self.search_query = query
        query_lower = query.lower()
        return [p for p in self.products 
                if query_lower in p.name.lower() or query_lower in p.description.lower()]
    
    def get_product_by_id(self, product_id: int) -> Optional[Product]:
        """Get product by ID"""
        return next((p for p in self.products if p.id == product_id), None)
    
    def get_categories(self) -> List[str]:
        """Get list of all categories"""
        return list(set(p.category for p in self.products))
    
    def change_view(self, view: str) -> Dict[str, Any]:
        """Change current view"""
        valid_views = ["products", "cart", "checkout"]
        if view not in valid_views:
            return {"success": False, "message": f"Invalid view. Choose from {valid_views}"}
        
        self.current_view = view
        return {"success": True, "message": f"Switched to {view} view"}
    
    def add_conversation_message(self, role: str, content: str):
        """Add message to conversation history"""
        self.conversation_history.append({
            "role": role,
            "content": content,
            "timestamp": datetime.now().isoformat()
        })
    
    def get_state_summary(self) -> str:
        """Get human-readable state summary"""
        summary = f"""
=== E-Commerce UI State ===
Current View: {self.current_view}
Products in Catalog: {len(self.products)}
Categories: {', '.join(self.get_categories())}
Cart Items: {len(self.cart)}
Cart Total: ${self.get_cart_total():.2f}
Active Filters: {self.active_filters if self.active_filters else 'None'}
Search Query: {self.search_query if self.search_query else 'None'}
Selected Category: {self.selected_category if self.selected_category else 'All'}
===========================
"""
        return summary
